[package]
name = "hello-world-rs"
version = "0.1.0"
authors = ["Armin Grodon <me@armingrodon.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
